# .github/workflows/deploy-pages.yml
name: 🚀 Deploy Dashboard to GitHub Pages

on:
  # Déclenché après chaque mise à jour de l'écosystème
  workflow_run:
    workflows: ["🌍 Digital Ecosystem", "📊 Ecosystem Dashboard"]
    types:
      - completed
  
  # Déploiement manuel
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare Dashboard Files
        run: |
          # Créer la structure pour GitHub Pages
          mkdir -p _site
          
          # Copier le dashboard et les données
          if [ -d ".ecosystem/dashboard" ]; then
            cp -r .ecosystem/dashboard/* _site/
          fi
          
          # Copier les données analytiques pour l'accès depuis le dashboard
          if [ -d ".ecosystem/analytics" ]; then
            mkdir -p _site/analytics
            cp -r .ecosystem/analytics/* _site/analytics/
          fi
          
          # Copier les visualisations
          if [ -d ".ecosystem/visualizations" ]; then
            mkdir -p _site/visualizations
            cp -r .ecosystem/visualizations/* _site/visualizations/
          fi
          
          # Copier le rapport principal
          if [ -f "ECOSYSTEM_REPORT.md" ]; then
            cp ECOSYSTEM_REPORT.md _site/
          fi
          
          # Créer un index.html si nécessaire
          if [ ! -f "_site/index.html" ]; then
            cat > _site/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>🌍 Digital Ecosystem</title>
    <meta http-equiv="refresh" content="0; url=./index.html">
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .message {
            text-align: center;
            padding: 20px;
        }
        a {
            color: white;
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="message">
        <h1>🌍 Digital Ecosystem</h1>
        <p>Loading dashboard...</p>
        <p>If you are not redirected, <a href="./index.html">click here</a>.</p>
    </div>
</body>
</html>
EOF
          fi
          
          # Ajuster les chemins dans les fichiers HTML pour GitHub Pages
          find _site -name "*.html" -type f -exec sed -i 's|href="/|href="./|g' {} \;
          find _site -name "*.html" -type f -exec sed -i 's|src="/|src="./|g' {} \;
          
          # Afficher la structure créée
          echo "📁 Site structure:"
          ls -la _site/
          
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Summary
        run: |
          echo "## 🚀 Dashboard Deployed!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🌐 **Live Dashboard:** https://batmac.github.io/digital-ecosystem/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Available Pages:" >> $GITHUB_STEP_SUMMARY
          echo "- [Main Dashboard](https://batmac.github.io/digital-ecosystem/index.html)" >> $GITHUB_STEP_SUMMARY
          echo "- [Timeline View](https://batmac.github.io/digital-ecosystem/timeline.html)" >> $GITHUB_STEP_SUMMARY
          echo "- [Ecosystem Report](https://batmac.github.io/digital-ecosystem/ECOSYSTEM_REPORT.md)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The dashboard updates automatically after each ecosystem cycle! 🔄" >> $GITHUB_STEP_SUMMARY